import type {
  AccountSummary,
  BudgetSummary,
  CashFlowDatum,
  DashboardMetric,
  InstitutionSummary,
  SpendingCategoryDatum,
  SubscriptionSummary,
  TransactionRecord,
} from "@/lib/types/finance";

export const dashboardMetrics: DashboardMetric[] = [
  {
    label: "Spent so far",
    amount: 4328.12,
    changeLabel: "12% below last month",
    trend: "down",
  },
  {
    label: "Income received",
    amount: 7850,
    changeLabel: "4% above last month",
    trend: "up",
  },
  {
    label: "Money left",
    amount: 3521.88,
    changeLabel: "Available for the rest of the month",
    trend: "up",
  },
];

export const spendingByCategory: SpendingCategoryDatum[] = [
  { category: "Housing", amount: 1900, color: "var(--chart-1)" },
  { category: "Food", amount: 620, color: "var(--chart-2)" },
  { category: "Transport", amount: 372, color: "var(--chart-3)" },
  { category: "Shopping", amount: 511, color: "var(--chart-4)" },
  { category: "Utilities", amount: 298, color: "var(--chart-5)" },
  { category: "Software", amount: 144.12, color: "#64748b" },
];

export const cashFlowSeries: CashFlowDatum[] = [
  { label: "Mar 3", income: 2100, spending: 980 },
  { label: "Mar 10", income: 1800, spending: 1225 },
  { label: "Mar 17", income: 1975, spending: 1060 },
  { label: "Mar 24", income: 1975, spending: 1063.12 },
];

export const transactions: TransactionRecord[] = [
  {
    id: "txn_1",
    userId: "user_1",
    plaidItemId: "item_chase",
    plaidAccountId: "acc_checking",
    plaidTransactionId: "plaid_txn_1",
    accountName: "Chase Checking",
    date: "2026-03-25",
    amount: 68.43,
    direction: "debit",
    merchantName: "Whole Foods",
    displayName: "Whole Foods Market",
    categoryPrimary: "Food",
    categoryDetailed: "Groceries",
    pending: false,
    isRecurring: false,
    createdAt: "2026-03-25T12:00:00.000Z",
    updatedAt: "2026-03-25T12:00:00.000Z",
  },
  {
    id: "txn_2",
    userId: "user_1",
    plaidItemId: "item_chase",
    plaidAccountId: "acc_checking",
    plaidTransactionId: "plaid_txn_2",
    accountName: "Chase Checking",
    date: "2026-03-24",
    amount: 15.49,
    direction: "debit",
    merchantName: "Netflix",
    displayName: "Netflix",
    categoryPrimary: "Entertainment",
    categoryDetailed: "Streaming",
    pending: false,
    isRecurring: true,
    createdAt: "2026-03-24T09:10:00.000Z",
    updatedAt: "2026-03-24T09:10:00.000Z",
  },
  {
    id: "txn_3",
    userId: "user_1",
    plaidItemId: "item_chase",
    plaidAccountId: "acc_checking",
    plaidTransactionId: "plaid_txn_3",
    accountName: "Chase Checking",
    date: "2026-03-23",
    amount: 185,
    direction: "debit",
    merchantName: "Equinox",
    displayName: "Equinox Membership",
    categoryPrimary: "Health",
    categoryDetailed: "Gym",
    pending: false,
    isRecurring: true,
    createdAt: "2026-03-23T08:45:00.000Z",
    updatedAt: "2026-03-23T08:45:00.000Z",
  },
  {
    id: "txn_4",
    userId: "user_1",
    plaidItemId: "item_chase",
    plaidAccountId: "acc_checking",
    plaidTransactionId: "plaid_txn_4",
    accountName: "Chase Checking",
    date: "2026-03-22",
    amount: 2400,
    direction: "credit",
    merchantName: "Northstar Studio",
    displayName: "Payroll Deposit",
    categoryPrimary: "Income",
    categoryDetailed: "Salary",
    pending: false,
    isRecurring: false,
    createdAt: "2026-03-22T14:00:00.000Z",
    updatedAt: "2026-03-22T14:00:00.000Z",
  },
  {
    id: "txn_5",
    userId: "user_1",
    plaidItemId: "item_amex",
    plaidAccountId: "acc_amex",
    plaidTransactionId: "plaid_txn_5",
    accountName: "Amex Gold",
    date: "2026-03-21",
    amount: 124.8,
    direction: "debit",
    merchantName: "Delta",
    displayName: "Delta Air Lines",
    categoryPrimary: "Travel",
    categoryDetailed: "Flights",
    pending: true,
    isRecurring: false,
    createdAt: "2026-03-21T20:00:00.000Z",
    updatedAt: "2026-03-21T20:00:00.000Z",
  },
  {
    id: "txn_6",
    userId: "user_1",
    plaidItemId: "item_chase",
    plaidAccountId: "acc_checking",
    plaidTransactionId: "plaid_txn_6",
    accountName: "Chase Checking",
    date: "2026-03-20",
    amount: 57.24,
    direction: "debit",
    merchantName: "Uber",
    displayName: "Uber",
    categoryPrimary: "Transport",
    categoryDetailed: "Rideshare",
    pending: false,
    isRecurring: false,
    createdAt: "2026-03-20T18:10:00.000Z",
    updatedAt: "2026-03-20T18:10:00.000Z",
  },
  {
    id: "txn_7",
    userId: "user_1",
    plaidItemId: "item_chase",
    plaidAccountId: "acc_checking",
    plaidTransactionId: "plaid_txn_7",
    accountName: "Chase Checking",
    date: "2026-03-18",
    amount: 11.99,
    direction: "debit",
    merchantName: "Spotify",
    displayName: "Spotify Premium",
    categoryPrimary: "Entertainment",
    categoryDetailed: "Music",
    pending: false,
    isRecurring: true,
    createdAt: "2026-03-18T07:00:00.000Z",
    updatedAt: "2026-03-18T07:00:00.000Z",
  },
  {
    id: "txn_8",
    userId: "user_1",
    plaidItemId: "item_chase",
    plaidAccountId: "acc_checking",
    plaidTransactionId: "plaid_txn_8",
    accountName: "Chase Checking",
    date: "2026-03-16",
    amount: 16,
    direction: "debit",
    merchantName: "Figma",
    displayName: "Figma Professional",
    categoryPrimary: "Software",
    categoryDetailed: "Design Tools",
    pending: false,
    isRecurring: true,
    createdAt: "2026-03-16T07:00:00.000Z",
    updatedAt: "2026-03-16T07:00:00.000Z",
  },
];

export const budgetSummaries: BudgetSummary[] = [
  {
    id: "budget_housing",
    categoryPrimary: "Housing",
    limitAmount: 2000,
    spentAmount: 1900,
    remainingAmount: 100,
    state: "warning",
  },
  {
    id: "budget_food",
    categoryPrimary: "Food",
    limitAmount: 850,
    spentAmount: 620,
    remainingAmount: 230,
    state: "on_track",
  },
  {
    id: "budget_transport",
    categoryPrimary: "Transport",
    limitAmount: 300,
    spentAmount: 372,
    remainingAmount: -72,
    state: "over",
  },
  {
    id: "budget_shopping",
    categoryPrimary: "Shopping",
    limitAmount: 650,
    spentAmount: 511,
    remainingAmount: 139,
    state: "on_track",
  },
  {
    id: "budget_entertainment",
    categoryPrimary: "Entertainment",
    limitAmount: 200,
    spentAmount: 164.48,
    remainingAmount: 35.52,
    state: "warning",
  },
];

export const subscriptionSummaries: SubscriptionSummary[] = [
  {
    id: "sub_netflix",
    merchantName: "Netflix",
    averageAmount: 15.49,
    frequency: "monthly",
    lastChargeDate: "2026-03-24",
    nextChargeDate: "2026-04-24",
    confidence: 0.95,
  },
  {
    id: "sub_spotify",
    merchantName: "Spotify",
    averageAmount: 11.99,
    frequency: "monthly",
    lastChargeDate: "2026-03-18",
    nextChargeDate: "2026-04-18",
    confidence: 0.94,
  },
  {
    id: "sub_figma",
    merchantName: "Figma",
    averageAmount: 16,
    frequency: "monthly",
    lastChargeDate: "2026-03-16",
    nextChargeDate: "2026-04-16",
    confidence: 0.91,
  },
  {
    id: "sub_equinox",
    merchantName: "Equinox",
    averageAmount: 185,
    frequency: "monthly",
    lastChargeDate: "2026-03-23",
    nextChargeDate: "2026-04-23",
    confidence: 0.83,
  },
];

export const connectedInstitutions: InstitutionSummary[] = [
  {
    id: "inst_1",
    plaidItemId: "item_chase",
    institutionName: "Chase",
    accountCount: 2,
    status: "healthy",
    lastSyncAt: "2026-03-26T09:42:00.000Z",
  },
  {
    id: "inst_2",
    plaidItemId: "item_amex",
    institutionName: "American Express",
    accountCount: 1,
    status: "requires_reauth",
    lastSyncAt: "2026-03-25T20:18:00.000Z",
  },
];

export const connectedAccounts: AccountSummary[] = [
  {
    id: "acc_checking",
    institutionName: "Chase",
    name: "Chase Checking",
    mask: "8421",
    type: "Depository",
    subtype: "Checking",
    currentBalance: 8424.62,
    availableBalance: 8132.11,
    syncStatus: "healthy",
  },
  {
    id: "acc_savings",
    institutionName: "Chase",
    name: "Reserve Savings",
    mask: "1142",
    type: "Depository",
    subtype: "Savings",
    currentBalance: 18420.23,
    availableBalance: 18420.23,
    syncStatus: "healthy",
  },
  {
    id: "acc_amex",
    institutionName: "American Express",
    name: "Amex Gold",
    mask: "2005",
    type: "Credit",
    subtype: "Credit Card",
    currentBalance: 1143.18,
    syncStatus: "requires_reauth",
  },
];

export const appSummary = {
  userName: "Jay",
  activeBudgetMonth: "March 2026",
  lastSyncAt: "2026-03-26T09:42:00.000Z",
  syncWindowLabel: "Updated Mar 26 at 9:42 AM",
  recurringMerchantCount: subscriptionSummaries.length,
  transactionCount: transactions.length,
};
